// <auto-generated />
using System;
using HelpdeskAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpdeskAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Helpdesk.API.Models.Agent", b =>
                {
                    b.Property<int>("agentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("agentId"));

                    b.Property<DateTime>("agentCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("agentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("agentId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Helpdesk.API.Models.Customer", b =>
                {
                    b.Property<int>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customerId"));

                    b.Property<DateTime>("customerCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("customerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Helpdesk.API.Models.Ticket", b =>
                {
                    b.Property<int>("ticketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ticketId"));

                    b.Property<int?>("agentFk")
                        .HasColumnType("int");

                    b.Property<DateTime?>("closedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerFk")
                        .HasColumnType("int");

                    b.Property<DateTime?>("resolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ticketDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ticketId");

                    b.HasIndex("agentFk");

                    b.HasIndex("customerFk");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Helpdesk.API.Models.TicketEvent", b =>
                {
                    b.Property<int>("ticketEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ticketEventId"));

                    b.Property<int?>("agentFk")
                        .HasColumnType("int");

                    b.Property<int?>("agentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("eventChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("newStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ticketFk")
                        .HasColumnType("int");

                    b.Property<int?>("ticketId")
                        .HasColumnType("int");

                    b.HasKey("ticketEventId");

                    b.HasIndex("agentId");

                    b.HasIndex("ticketFk");

                    b.HasIndex("ticketId");

                    b.ToTable("TicketEvents");
                });

            modelBuilder.Entity("Helpdesk.API.Models.Ticket", b =>
                {
                    b.HasOne("Helpdesk.API.Models.Agent", "Agent")
                        .WithMany("Tickets")
                        .HasForeignKey("agentFk");

                    b.HasOne("Helpdesk.API.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("customerFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Helpdesk.API.Models.TicketEvent", b =>
                {
                    b.HasOne("Helpdesk.API.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("agentId");

                    b.HasOne("Helpdesk.API.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("ticketFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpdesk.API.Models.Ticket", null)
                        .WithMany("TicketEvents")
                        .HasForeignKey("ticketId");

                    b.Navigation("Agent");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Helpdesk.API.Models.Agent", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Helpdesk.API.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Helpdesk.API.Models.Ticket", b =>
                {
                    b.Navigation("TicketEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
